feat: 내 쿠폰함 기능 관련 (작업중!!!)
Zanit-Development/Zanit_FE pull request #129
Opened 2023-10-10 07:48 UTC by oxxun21

### 🤚 잠깐!
- [ ] PR 제목 형식 확인 [`feat: 기능 추가`]
- [ ] 이슈 등록 확인
- [ ] 라벨 등록 확인

## ✏️ PR 요약
- [ ] 기능 추가 :
- [ ] 마크업 & 스타일 :
- [ ] 리팩토링 :
- [ ] 문서 수정 :
- [ ] 버그 수정 :
- [ ] 도와주세요 :
- [ ] 개발 환경 세팅 :

<br>

## 💡 상세 작업 내용

-
-

<br>

## 🌟 전달 사항

- 미리 올려둔 거임요!!!

<br>

## ⚠️ Issue Number
- #128 

<br><br>

2023-10-24 13:56 UTC, jypark38 requested changes
고생하셨슴닷

2023-10-24 13:56 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +  const subscribeEnd = new Date(userInfo.subsEndDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
안바까도 되고 걍 코멘트인데, 함수 하나 두고 쓰는거도 나쁘지 않을거 같아용

2023-10-24 13:56 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +  const expDateFormatted = expDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" });
Q : {month:"long", day:"numeric"} 이거 지정하면 어떻게 돼요?

2023-10-24 13:56 UTC, jypark38 commented on src/components/coupon/ManualPaymentBtn.tsx
> +        <Button {...BUTTON_OPTIONS.EXTEND_COUPON} onClick={subscribeStartPage} />
memo : 나중에 분기처리 필요함 (+benefitNote)

2023-10-24 13:56 UTC, jypark38 commented on src/components/coupon/UseHistory.tsx
> +            )}
Q : && 비교 없애고 usedCoupon?.map 으로 하면 오류나려나용

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
price.toLocaleString();
도 가능할듯?.?

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const price = 29000;
29900 입니당

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/PopupPromotion.tsx
>  export const PopupPromotion = ({ ...props }) => {
이거는 확인을 해봐야하는데 X멤버십(정기결제)만 해당되는 페이지일수도 있을거 같아요

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/StopMembership.tsx
> +export const StopMembership = ({ userInfo }: { userInfo: UserInfoType }) => {
이거도 마찬가지로.. X멤버십(정기결제)만 해당되는 페이지일수도..

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
요거도 29900

price.toLocaleString();
이러케도 될거에여

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +  const subscribeEnd = new Date(userInfo.subsEndDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
위에 비슷한 기능을 하든게 있는거 같았는데 화긴해주세용

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/StopMembership.tsx
> +  const subscribeEnd = new Date(userInfo.subsEndDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
중복코드 체크

2023-10-24 13:56 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +        <li>다음 결제 예정일 : &#91;{subscribeEnd}&#93;</li>
이건 코드리뷰라기보단.. 어떻게 생각하는지 여쭤보는건데
보통 구독 만료일 당일에 다음 결제가 되나요?

2023-10-24 13:56 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +  subsEndDate.setDate(subsEndDate.getDate() + 1);
👍🏻
만료일 다음날로 띄우는게 맞는지만 체크하면 될것 같아유

2023-10-24 14:02 UTC, jypark38 reviewed
ㅜㅜ

2023-10-24 14:02 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +export const MembershipInfo = ({ userInfo }: { userInfo: UserInfoType }) => {
이거도... 정기결제만 해당이 아닐지......ㅜㅜ

2023-10-24 14:12 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
+ discount, price, formattedPrice, 39,900 이런거 여러군데서 쓰이기도 하는 상수니까
모아서 관리해보리는건 어떨찌..🫥

2023-10-24 14:27 UTC, oxxun21 commented on src/components/coupon/HasCoupon.tsx
> +  const subscribeEnd = new Date(userInfo.subsEndDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
그럴라구용,,,

2023-10-24 14:28 UTC, oxxun21 commented on src/components/coupon/HasCoupon.tsx
> +  const expDateFormatted = expDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" });
00월 00일로 표시대여!

2023-10-24 14:29 UTC, oxxun21 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
먼가 정규표현식 쓰는게 더 꼼꼼히(?) 될 거 같아서 저거 쓴건데 그게 더 나을려나요,,, 두개 먼 차이있는지 알아봐야할듯

2023-10-24 14:30 UTC, oxxun21 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const price = 29000;
앟

2023-10-24 14:30 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +  const expDateFormatted = expDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" });
Q : 
```js
const subscribeStart = new Date(userInfo.subsStartDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
const subscribeEnd = new Date(userInfo.subsEndDate).toLocaleDateString().replace(/\./g, "").replace(/\s/g, ".");
```
디자인상 얘랑은 다른거에여?

2023-10-24 14:31 UTC, oxxun21 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +        <li>다음 결제 예정일 : &#91;{subscribeEnd}&#93;</li>
정기 결제는 보통 날짜 하루 정해서 결제하지 않나요,, 내 교통카드는 항상 10일에 나가고,,, 유튜브는 5일에 나가는데,,, 피그마 상에선 이렇게 되있더라구요

2023-10-24 14:33 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +        <li>다음 결제 예정일 : &#91;{subscribeEnd}&#93;</li>
요것도 무러봐야겠네여..

2023-10-24 14:34 UTC, oxxun21 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
차라리 이거 가격들을 리코일에 박아버릴까요...

2023-10-24 14:41 UTC, oxxun21 commented on src/components/coupon/HasCoupon.tsx
> +  const expDateFormatted = expDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" });
얘는 yyyy.mm.dd로 표시되고 쿠폰 사진 안에 있ㄴ는 애들은 mm월 dd일로 표시돼용

2023-10-24 14:42 UTC, oxxun21 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
생각 못하고 있었는데 그게 더 맞는거 같아용 그렇게 할께욥!

2023-10-24 14:42 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +  const expDateFormatted = expDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" });
감사합니답

2023-10-25 09:23 UTC, jypark38 commented on src/components/coupon/UseHistory.tsx
> +            )}
다른 방법으론 usedCoupon을 첨부터 useState([]) 로 초기화해놓으묜 && 비교가 업서도 될거같긴 함니다

2023-10-27 05:30 UTC, oxxun21 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
이거 toLocaleString은 number 타입이면 상관 없는데 string으로 들어오면 제대로 출력이 안된대용 가격들 관리하는 파일 프론트 단에서 저장해둘거면 사용해도 댈듯?

2023-10-27 06:27 UTC, oxxun21 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +export const MembershipInfo = ({ userInfo }: { userInfo: UserInfoType }) => {
이고 `{auto && <Link to="/stop-subscribe">멤버십 정기결제 해지하기</Link>}` 이렇게 되있어서 자동결제 아니면 이 페이지 안떠서 괜찮지 않을까,,, 합니당,,, 아까 카톡에서 말한게 이거 문제엿음ㅋㅋㅋ ㅜ

2023-10-27 06:32 UTC, jypark38 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +  const formattedPrice = price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
간님이 쓰기 편한걸로 선택해서 하는걸로 ㅎ_ㅎ

2023-10-27 06:34 UTC, jypark38 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +export const MembershipInfo = ({ userInfo }: { userInfo: UserInfoType }) => {
앟

그럼 url 직접 입력해서 들어올거만 대비해서 해지하기 페이지에 정기결제 멤버가 아니면 404로 redirect 시키는거 추가하는거는 어때요?

2023-10-27 06:56 UTC, oxxun21 commented on src/components/stopSubscribe/MembershipInfo.tsx
> +export const MembershipInfo = ({ userInfo }: { userInfo: UserInfoType }) => {
넵 해볼게요!

2023-10-27 07:21 UTC, oxxun21 commented on src/components/coupon/UseHistory.tsx
> +            )}
usedCoupon초기화할 때 UsedCouponListArr를 두지 않으면 i.속성 들한테서 다 오류가 ㅜㅜ,, && 비교는 없애고 usedCoupon?.map로 두는건 되네용! 고쳐서 올려두겠습니다~

2023-10-27 09:42 UTC, jypark38 approved these changes
고생하셨슴니다 ㅎㅎ

2023-10-27 09:42 UTC, jypark38 commented on src/components/stopSubscribe/PopupPromotion.tsx
> +              39,900원
[P5] : 정의해둔 옵션을 이용해도 괜찮을것 같아요 (Z)

2023-10-27 09:42 UTC, jypark38 commented on src/components/coupon/ManualPaymentBtn.tsx
> +      ) : null}
분기처리 다 마무리 된건가용?

2023-10-27 10:31 UTC, oxxun21 commented on src/pages/myCoupon/MyCoupon.tsx
> +      const userRes = await userInfoAPI();
아항 해보구 수정해서 올린 담 머지할께욥!

2023-10-27 10:33 UTC, oxxun21 commented on src/components/coupon/ManualPaymentBtn.tsx
> +      ) : null}
자동결제 데이터 어떻게 들어오냐에 따라서 그것만 맞추면 아마두 다,,, 된거 같아용 이후에 또 확인은 해봐야할 것 같긴한데 ㅋㅋㅜ

2023-10-27 10:42 UTC, jypark38 commented on src/components/coupon/ManualPaymentBtn.tsx
> +      ) : null}
그 아마 정기결제냐 아니면 저렴한 구독 어쩌구 메세지 띄울수 있게 해야하구, 연장하기 버튼 없어야 할거에욤
체크만 해놔주세용

2023-10-27 10:52 UTC, oxxun21 commented on src/components/coupon/ManualPaymentBtn.tsx
> +      ) : null}
그부분들 자동결제 인지 아닌지로 처리해놨어용

2023-10-27 10:53 UTC, merged