design : 자동, 수동 결제에 따른 쿠폰함 UI
Zanit-Development/Zanit_FE pull request #66
Opened 2023-08-28 14:50 UTC by oxxun21

### 🤚 잠깐!
- [x] PR 제목 형식 확인 [`feat: 기능 추가`]
- [x] 이슈 등록 확인
- [x] 라벨 등록 확인

## ✏️ PR 요약
- [ ] 기능 추가 :
- [x] 마크업 & 스타일 :
- [ ] 리팩토링 :
- [ ] 문서 수정 :
- [ ] 버그 수정 :
- [ ] 도와주세요 :
- [ ] 개발 환경 세팅 :

<br>

## 🌟 전달 사항

- 자동/수동, 쿠폰 사용 여부는 boolean 변수로 되어있습니다

<br>

## ⚠️ Issue Number
- #32 

<br/>

## 💡 상세 작업 내용

<img src="https://github.com/Zanit-Development/Zanit_FE/assets/98699927/aefbb735-fad6-48c5-9214-2befe9efc233" align="left" width="45%">
<img src="https://github.com/Zanit-Development/Zanit_FE/assets/98699927/1f38e00b-2e51-47b7-a330-bd50697bba22" align="right" width="45%">

<br/>

<img src="https://github.com/Zanit-Development/Zanit_FE/assets/98699927/2060590f-5a52-45c9-8fb0-81a1030ddcf2" align="left" width="45%">
<img src="https://github.com/Zanit-Development/Zanit_FE/assets/98699927/e69e54d8-e071-4961-b225-a53476be20812" align="right" width="45%">

<br/>

2023-08-29 05:23 UTC, jypark38 requested changes
확인했습니다

2023-08-29 05:23 UTC, jypark38 commented on src/components/coupon/HasCoupon.tsx
> +        )}
[P2] use 여부는 use로 통제하고
p태그 안에만 분기처리 해도 좋을거 같습니다

2023-08-30 06:47 UTC, oxxun21 commented on src/components/coupon/HasCoupon.tsx
> +        )}
반영 해낫읍니다

2023-08-30 06:47 UTC, jypark38 approved these changes
굿!!

2023-08-30 06:48 UTC, merged